### ISSUE TITLE
Proper SHA3 implementation?

### ISSUE THREAD

**Issue by iagox86** [havenwood/sha3-pure-ruby#1]
Hey,

I'm trying to find a SHA3 library for Ruby, but it seems like every library (this one included) is, if I'm not mistaken, using an old version of Keccak for validation, not the actual standardized SHA3.

The most recent SHA3 test vectors say that the hash of the blank string should be:

A7FFC6F8BF1ED76651C14756A061D662F580FF4DE43B49FA82D80A4B80F8434A

however, in this library, it works out to:

C5D2460186F7233C927E7DB2DCC703C0E500B653CA82273B7BFAD8045D85A470 

After some research, I found some pages that calculate both the original keccak and the sha3, and it confirms that the first output is correct. Here's one such page:

https://www.npmjs.com/package/js-sha3

And here's a blank test vector from the original docs:

http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA3-256_Msg0.pdf

Which agrees with everything else, and shows that the output is wrong.

Is there any chance of getting this fixed? Or of adding an option to use the new variation?

**Comment by iagox86** [comment]
It appears to be a padding issue.. NIST changed the padding to be:

```
SHA3-256(M) = K ECCAK [512] (M || 01, 256);
```

But this implementation doesn't account for the 01 in the padding.

I made a very small change to the library, but confirmed it works with all the NIST test vectors:

```
diff --git a/lib/sha3-pure-ruby.rb b/lib/sha3-pure-ruby.rb
index d773612..403b42a 100644
--- a/lib/sha3-pure-ruby.rb
+++ b/lib/sha3-pure-ruby.rb
@@ -41,7 +41,7 @@ module Digest
       width = 200 - @size * 2

       buffer = @buffer
-      buffer << "\x01" << "\0" * (width - buffer.size % width)
+      buffer << "\x06" << "\0" * (width - buffer.size % width)
       buffer[-1] = (buffer[-1].ord | 0x80).chr

       0.step buffer.size - 1, width do |j|
```

06 is 00000110 - in reverse byte order, it's 01100000 - the 01 is what NIST added, and the 1.... padding is what's in the original (already implemented)

Hope this helps!

**Comment by skull-squadron** [comment]
Also, here's some links for working FIPS 202 SHA3-nnn online calculators to double-check:

http://emn178.github.io/online-tools/sha3_224.html
http://emn178.github.io/online-tools/sha3_256.html
http://emn178.github.io/online-tools/sha3_512.html
http://emn178.github.io/online-tools/sha3_384.html
